repository:
  name: test-repository
  description: A test repository to try out different GitHub related workflows
  topics: github

  private: false

  has_issues: true
  has_projects: false
  has_wiki: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

  delete_branch_on_merge: true

  allow_auto_merge: true

  default_branch: main


branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - test
      enforce_admins: false    
      required_linear_history: true
      restrictions: null
